name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: meta-introspector/checkout@main
      - uses: ./.github/actions/install-dependencies
      - run: npm run style:check
      - run: npm test
